export const run = () => {
  throw new Error("an error occurred");
};
